# Generated by Django 4.1.1 on 2022-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="age",
            field=models.IntegerField(
                blank=True, default=0, editable=False, null=True, verbose_name="Age"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="contact_number",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=12,
                null=True,
                verbose_name="Contact Number",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="post",
            name="doctors_request",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="Link of doctors request",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="email_address",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Examination 1", "Examination 1"),
                    ("Examination 2", "Examination 2"),
                    ("Examination 3", "Examination 3"),
                ],
                max_length=100,
                null=True,
                verbose_name="Examination Type",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hospital_site",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hospital A", "Hospital A"),
                    ("Hospital B", "Hospital B"),
                    ("Hospital C", "Hospital C"),
                ],
                max_length=100,
                null=True,
                verbose_name="Select site",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Middle Name"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="preferred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Preferred Date"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="procedure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Procedure 1", "Procedure 1"),
                    ("Procedure 2", "Procedure 2"),
                    ("Procedure 3", "Procedure 3"),
                ],
                max_length=100,
                null=True,
                verbose_name="Procedure",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="radiologist_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name="Radiologist",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="radtech_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name="Radiologic Technologist",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="requesting_physician",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Requesting Physician",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=100,
                null=True,
                verbose_name="Sex",
            ),
        ),
    ]
