# Generated by Django 4.1.1 on 2022-11-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_age_post_contact_number_post_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reference_no",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Reference No."
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="post",
            name="contact_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Contact Number"
            ),
        ),
    ]
