# Generated by Django 4.1.1 on 2022-11-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_reference_no_alter_post_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.RemoveField(model_name="post", name="content",),
        migrations.RemoveField(model_name="post", name="date_posted",),
        migrations.RemoveField(model_name="post", name="title",),
    ]
