# Generated by Django 4.1.1 on 2022-12-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_exam_type_alter_post_procedure"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="reference_no",),
    ]
