# Generated by Django 4.1.1 on 2022-12-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_post_reference_no"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="age",),
    ]
