# Generated by Django 4.1.1 on 2022-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_exam_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Booked", "Booked"),
                    ("Confirmed", "Confirmed"),
                    ("Served", "Served"),
                ],
                default="Booked",
                max_length=100,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
