# Generated by Django 4.1.1 on 2022-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="procedure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Procedure 1", "Procedure 1"),
                    ("Procedure 2", "Procedure 2"),
                ],
                max_length=100,
                null=True,
                verbose_name="Procedure",
            ),
        ),
    ]
